"""Add created_by_admin_id to User model

Revision ID: 515dc8cdefc6
Revises: 
Create Date: 2025-09-16 22:48:54.210679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515dc8cdefc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by_admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_users_created_by_admin_id', 'users', 'users', ['created_by_admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_created_by_admin_id', 'users', type_='foreignkey')
    op.drop_column('users', 'created_by_admin_id')
    # ### end Alembic commands ###
