"""Add AdvanceSalary model

Revision ID: 52cfec5b69e5
Revises: cebb9c1a55f9
Create Date: 2026-03-31 23:10:00.752992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52cfec5b69e5'
down_revision: Union[str, None] = 'cebb9c1a55f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advance_salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advance_salaries_date'), 'advance_salaries', ['date'], unique=False)
    op.create_index(op.f('ix_advance_salaries_id'), 'advance_salaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advance_salaries_id'), table_name='advance_salaries')
    op.drop_index(op.f('ix_advance_salaries_date'), table_name='advance_salaries')
    op.drop_table('advance_salaries')
    # ### end Alembic commands ###
