"""Add ondelete cascade to user relationships

Revision ID: 62c5f63d97b7
Revises: 515dc8cdefc6
Create Date: 2025-09-16 23:03:33.147713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62c5f63d97b7'
down_revision: Union[str, None] = '515dc8cdefc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_employee', 'attendance_records', type_='foreignkey')
    op.drop_constraint('fk_user_attendance', 'attendance_records', type_='foreignkey')
    op.create_foreign_key('fk_attendance_user_id', 'attendance_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_attendance_employee_id', 'attendance_records', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('fk_user', 'employees', type_='foreignkey')
    op.create_foreign_key('fk_employees_user_id', 'employees', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('fk_user_holiday', 'holidays', type_='foreignkey')
    op.create_foreign_key('fk_holidays_user_id', 'holidays', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('fk_user_password_reset', 'password_resets', type_='foreignkey')
    op.create_foreign_key('fk_password_resets_user_id', 'password_resets', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.drop_constraint('fk_user_settings', 'settings', type_='foreignkey')
    op.create_foreign_key('fk_settings_user_id', 'settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_settings_user_id', 'settings', type_='foreignkey')
    op.create_foreign_key('fk_user_settings', 'settings', 'users', ['user_id'], ['id'])

    op.drop_constraint('fk_password_resets_user_id', 'password_resets', type_='foreignkey')
    op.create_foreign_key('fk_user_password_reset', 'password_resets', 'users', ['user_id'], ['id'])

    op.drop_constraint('fk_holidays_user_id', 'holidays', type_='foreignkey')
    op.create_foreign_key('fk_user_holiday', 'holidays', 'users', ['user_id'], ['id'])

    op.drop_constraint('fk_employees_user_id', 'employees', type_='foreignkey')
    op.create_foreign_key('fk_user', 'employees', 'users', ['user_id'], ['id'])

    op.drop_constraint('fk_attendance_employee_id', 'attendance_records', type_='foreignkey')
    op.drop_constraint('fk_attendance_user_id', 'attendance_records', type_='foreignkey')
    op.create_foreign_key('fk_user_attendance', 'attendance_records', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_employee', 'attendance_records', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###
