"""Remove automatic_overtime_hours from AttendanceRecord

Revision ID: cebb9c1a55f9
Revises: 1070c99cf034
Create Date: 2025-10-21 17:01:58.803491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cebb9c1a55f9'
down_revision: Union[str, None] = '1070c99cf034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('attendance_records', 'status',
    #            existing_type=postgresql.ENUM('Present', 'Absent', 'Half-day', name='attendance_status'),
    #            type_=sa.Enum('Present', 'Absent', 'HALF_DAY', name='attendancestatus'),
    #            existing_nullable=False)
    op.drop_column('attendance_records', 'automatic_overtime_hours')
    # op.alter_column('users', 'role',
    #            existing_type=postgresql.ENUM('admin', 'staff', name='user_role'),
    #            type_=sa.Enum('admin', 'staff', name='userrole'),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'admin'::user_role"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'role',
    #            existing_type=sa.Enum('admin', 'staff', name='userrole'),
    #            type_=postgresql.ENUM('admin', 'staff', name='user_role'),
    #            existing_nullable=False,
    #            existing_server_default=sa.text("'admin'::user_role"))
    op.add_column('attendance_records', sa.Column('automatic_overtime_hours', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True))
    # op.alter_column('attendance_records', 'status',
    #            existing_type=sa.Enum('Present', 'Absent', 'HALF_DAY', name='attendancestatus'),
    #            type_=postgresql.ENUM('Present', 'Absent', 'Half-day', name='attendance_status'),
    #            existing_nullable=False)
    # ### end Alembic commands ###
