"""Add company_logo_url to Settings model

Revision ID: eb39fa3e8132
Revises: 62c5f63d97b7
Create Date: 2025-09-18 17:38:30.338182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb39fa3e8132'
down_revision: Union[str, None] = '62c5f63d97b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('company_logo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'company_logo_url')
    # ### end Alembic commands ###
